config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'site#home'

  resources :users do
    resources :items
  end

   resources :items, only: [:index]

end

app/models/item.rb
class Item < ActiveRecord::Base

	has_many :participations
	has_many :users, through: :participations

	has_attached_file :picture, :styles => { :large => "355x255>", :medium => "290x220>", :thumb => "100x200>" }

	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
	validates_presence_of :name
end

app/models/participation.rb
class Participation < ActiveRecord::Base

	belongs_to :item
	belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :participations
	has_many :items, through: :participations

	has_attached_file :avatar, :styles => { :large => "120x120>", :medium => "48x48>", :thumb => "26x26>" }

	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :avatar
    devise_parameter_sanitizer.for(:sign_up) << :description
    devise_parameter_sanitizer.for(:sign_up) << :location
  end

   def after_sign_in_path_for(resource)
    items_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


	def new
		@item = Item.new
		@user = User.find(params[:user_id])
	end

	def create
		@user = User.find(params[:user_id])
		@item = Item.new(entry_params)
		@item.users << @user

		if @item.save
			flash[:notice] = "Item has been created succesfully"
			redirect_to items_path

		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:user_id])
		@item = Item.find(params[:id])
	end

	def index
		if params[:user_id]
		 	@user = User.find(params[:user_id])
			@items = @user.items
		else
			@items = Item.all
		end
	end

	private

	def entry_params
		params.require(:item).permit(:name, :picture, :price, :date, :description, :user_id)
	end


end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	def home
		render 'home', layout: false
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(entry_params)

		if @user.save
			flash[:notice] = "User has been created succesfully"
			render 'show'

		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def index
		@users = User.all
	end

private

	def entry_params
		params.require(:user).permit(:name, :avatar, :description, :location, :email)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/items/index.html.erb
<div id="list" class="row">
	<ul>
		<% @items.each do |item| %>
			<li id="item" class="col-md-4 col-xs-6">
				<div id="itemImg">
			   		<%= image_tag item.picture.url(:medium) %>
				</div>
					</br>
				<p id="itemName"> <%= item.name %> </p>
				</br>
				<%= item.description %>
				</br>
				<%= item.price %> €
				</br>
				<%= item.date %>
				</br>
				<div id="BtnItem">
					<button class= "btn btn-sm btn-success">Share it!</button>
					<button class= "btn btn-sm">View</button>
				</div>
			</li>
		<% end %>
	</ul>
</div>

app/views/items/new.html.erb
<% content_for :background do %>
  item
<% end %>


<% @item.errors.each do |field, error| %>
	<p><%= "#{field} #{error}" %></p>
<% end %>

<div>
	<div class="row">
	  	<div class="col-md-4 col-md-offset-4 bgray" style="padding: 30px">

			<%= form_for  [@user, @item] do |f| %>
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-control" %>
				</br>
				<%= f.label :picture %>
				<%= f.file_field :picture%>
				</br>
				<%= f.label :price %>
				<%= f.text_field :price, class: "form-control" %>
				</br>
				<%= f.label :date %> Until  when you want the item to be online.
				<%= f.date_select :date, {}, {:class => "form-control date"} %>
				</br>
				<%= f.label :description %> (optional)
				<%= f.text_field :description, class: "form-control" %>
				</br>
				<%= f.submit class: "btn btn-primary btn-sm" %>
			<% end %>
		</div>
	</div>
</div>

app/views/items/show.html.erb

<div class="row">
  	<div class="col-md-4 col-md-offset-4 bgray" style="padding: 30px">
       <%= image_tag @item.picture.url(:medium) %>
		<%= @item.name %>
		</br>
		<%= @item.date %>
		</br>
		<%= @item.description %>
		</br>
		<%= @item.price %> €
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareProject</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>


<body class="<%= yield :background %>">

  <%= render 'shared/navigation' %>

	<div class="container m-top">

		<% if flash[:notice].present? %>
		<p class="alert alert-success"><%= flash[:notice] %></p>
		<% end %>

		<%= yield %>
	</div>

	<!-- <footer>
		<ul class="menu">
			<li class="ib">Contact us</li>
			<li class="ib">Policy</li>
			<li class="ib">Save &amp; Share &copy;</li>
		</ul>
	</footer> -->

</body>

</html>

app/views/shared/_navigation.html.erb
<nav class='navbar navbar-fixed-top'>
  <div class='container' id='nav'>
    <div class='navbar-header'>
      <%= link_to image_tag('logo-small.png', alt:'logo'), items_path, class: 'logo' %>
    </div>

    <ul class='nav navbar-nav navbar-right' id='head-btn'>
      <% if user_signed_in? %>
        <li>
          <%= link_to "+ Create item", new_user_item_path(current_user)%>
        </li>
        <li>
          <%= link_to "My profile", user_path(current_user)%>
        </li>
        <li>
          <%= link_to "Logout", destroy_user_session_path, method: 'DELETE' %>
        </li>
        
      <% else %>
        <li>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "Sign in", new_user_session_path %>
        </li>
      <% end %>
    </ul>

    <div id='search'>
      <input type='search'>
    </div>

  </div>
</nav>

app/views/site/home.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>ShareProject</title>
	  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= stylesheet_link_tag  'home', media: 'all', 'data-turbolinks-track' => true %>
	  <meta name="viewport" content="width=device-width, initial-scale=1">

	</head>
	<body>

		<ul class="sm">
			<li class="ib ">Follow us: </li>
			<li class="ib fa fa-twitter" alt="Twitter"></li>
			<li class="ib fa fa-instagram"></li>
			<li class="ib fa fa-google-plus" alt="Google +"></li>
			<li class="ib fa fa-facebook" alt="Pinterest"></li>
		</ul>

		<div class="info">
			<%= image_tag("logo-big.png", :alt => "logo", class: "img-responsive") %>
			<p>Where you will save money sharing with friends.</p>
			<div class="buttons-home">
			<%= link_to 'Sign in', new_user_session_path , class: "btn btn-default" %>
			<%= link_to 'Sign up', new_user_registration_path, method: 'GET',class: "btn btn-primary" %>
			</div>
		</div>

		<footer>
			<ul class="menu">
				<li class="ib">Contact us</li>
				<li class="ib">Policy</li>
				<li class="ib">Save &amp; Share &copy;</li>
			</ul>
		</footer>

	</body>
</html>









app/views/users/edit.html.erb

<% content_for :background  do %>
	user
<% end %>

<% @user.errors.each do |field, error| %>
	<p><%= "#{field} #{error}" %></p>
<% end %>

	<div>
		<div class="row">
		  	<div class="col-md-4 col-md-offset-4 bgray" style="padding: 30px">

		  		<h1>Welcome new user!</h1>

				<%= form_for @user do |f| %>
					<%= f.label :avatar %>
					<%= f.file_field :avatar %>
					</br>
					<%= f.label :name %>
					<%= f.text_field :name, class: "form-control" %>
					</br>
					<%= f.label :email %>
					<%= f.text_field :email, class: "form-control" %>
					</br>
					<%= f.label :location %>
					<%= f.select(:location, ['Barcelona', 'Madrid', 'Valencia', 'Sevilla'], {}, {:class => 'form-control mtop'})%>
					</br>
					<%= f.label :description %> (optional)
					<%= f.text_field :description, class: "form-control" %>
					</br>
					<%= f.submit class: "btn btn-primary btn-sm" %>
				<% end %>
			</div>
		</div>
</div>
</main>

app/views/users/index.html.erb
<%= content_for	:header do %>
	<div class="container" id="nav">
		<div id="logo">
			<%= image_tag("logo-small.png", alt: "logo") %>
		</div>
		<div id="head-btn">
			<a class= "btn btn-primary" href="users/1/items/new">+ Create item</a>
			<a class= "btn btn-secondary" href="users/new">New user</a>
		</div>
		<div id="search">
			<input type="search" placeholder="Search"/>
		</div>
	</div>
<% end %>

<div id="users_list" class="row">
	<ul>
		<% @users.each do |user| %>
		  	<div class="col-md-4 col-xs-6 bg-gray" style="padding: 30px">
				<%= image_tag user.avatar.url(:large), class: "img-rounded" %>
				<div id="info-user">
				</br>
					<h4>Name:</h4>
					<p><%= user.name %></p>
					</br>
					<h4>Location:</h4>
					<p><%= user.location %></p>
					</br>
					<h4>Email:</h4>
					<p><%= user.email %></p>
					</br>
					<h4>Description:</h4>
					<p><%= user.description %></p>
					</br>
				</div>
			</div>
		<% end %>
	</ul>
</div>

app/views/users/new.html.erb
<% content_for :background  do %>
	user
<% end %>

<% @user.errors.each do |field, error| %>
	<p><%= "#{field} #{error}" %></p>
<% end %>

	<div>
		<div class="row">
		  	<div class="col-md-4 col-md-offset-4 bgray" style="padding: 30px">

		  		<h1>Welcome new user!</h1>

				<%= form_for @user do |f| %>
					<%= f.label :avatar %>
					<%= f.file_field :avatar %>
					</br>
					<%= f.label :name %>
					<%= f.text_field :name, class: "form-control" %>
					</br>
					<%= f.label :email %>
					<%= f.text_field :email, class: "form-control" %>
					</br>
					<%= f.label :location %>
					<%= f.select(:location, ['Barcelona', 'Madrid', 'Valencia', 'Sevilla'], {}, {:class => 'form-control mtop'})%>
					</br>
					<%= f.label :description %> (optional)
					<%= f.text_field :description, class: "form-control" %>
					</br>
					<%= f.submit class: "btn btn-primary btn-sm" %>
				<% end %>
			</div>
		</div>
</div>
</main>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 bg-gray" style="padding: 30px">
		<%= image_tag @user.avatar.url(:large), class: "img-rounded" %>
		<div id="info-user">
			</br>
			<h4>Name:</h4>
			<p><%= @user.name %></p>
			</br>
			<h4>Location:</h4>
			<p><%= @user.location %></p>
			</br>
			<h4>Email:</h4>
			<p><%= @user.email %></p>
			</br>
			<h4>Description:</h4>
			<p><%= @user.description %></p>
			</br>
		</div>
		<div>
			<a class= "btn btn-secondary" href="/../items"> < Go to index</a>
			<%= link_to('Edit',  edit_user_registration_path(current_user), class: "btn btn-secondary")  %>
			<%= link_to('My items', user_items_path(current_user), class: "btn btn-secondary")  %>
		</div>
	</div>
</div>